version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "8080:8080"
    env_file:
      - vars.env
    depends_on:
      - mongo
  mongo:
      image: mongo:4.4.1
      restart: always
      command: --configExpand rest
      ports:
          - 27017:27017
      logging:
          driver: none
